services:
  app:
    env_file:
      - ../backend/.env
    build:
      context: ..
      dockerfile: ../Dockerfile
    ports:
      - "2450:2450"
    environment:
      - NODE_ENV=production
      - PORT=2450
    depends_on:
      - db
      - redis
    networks:
      - mini-wallet-network

  db:
    env_file:
      - ../backend/.env
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-mini_wallet}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mini-wallet-network

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    networks:
      - mini-wallet-network

networks:
  mini-wallet-network:

volumes:
  db_data:
  redis_data: