version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://user:password@db:5432/mini_wallet
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret
      - PORT=3000
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    networks:
      - mini-wallet-network

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mini_wallet
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
volumes:
  db_data:
  redis_data: