## Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{username}}",
  "password": "{{password}}"
}


### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "{{username}}",
  "password": "{{password}}"
}